spring:
  config:
    activate:
      on-profile: "dev"

service:
    env: dev
    name: event-service
    createdBy: john.doe
    createdAt: 2020-01-01
    author:
      name: John Doe
      title: Software Engineer
    url:
      - http://localhost:2222
      - http://localhost:3333